name: Debug

on:
  push:
    branches: [main]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug Info
        run: |
          echo "=== Debug Information ==="
          echo "Event: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "Workspace: ${{ github.workspace }}"
          echo "========================"

      - name: List Files
        run: |
          echo "=== File Structure ==="
          ls -la
          echo "====================="

      - name: Check package.json
        run: |
          echo "=== package.json ==="
          cat package.json
          echo "===================="

      - name: Check pnpm-lock.yaml
        run: |
          echo "=== pnpm-lock.yaml (first 10 lines) ==="
          head -10 pnpm-lock.yaml
          echo "====================================="

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Show versions
        run: |
          echo "=== Versions ==="
          node --version
          pnpm --version
          echo "==============="

      - name: Install dependencies
        run: |
          echo "=== Installing dependencies ==="
          pnpm install --frozen-lockfile
          echo "==============================="

      - name: List node_modules
        run: |
          echo "=== node_modules structure ==="
          ls -la node_modules/.bin/ | head -10
          echo "============================="

      - name: Test scripts
        run: |
          echo "=== Testing scripts ==="
          pnpm run --help
          echo "======================"

      - name: Success
        run: echo "Debug completed successfully!"
