name: Release Only

on:
  push:
    branches: [main]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Show versions
        run: |
          echo "Node version: $(node --version)"
          echo "pnpm version: $(pnpm --version)"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Show current version
        run: |
          echo "Current package.json version:"
          node -p "require('./package.json').version"

      - name: Show recent commits
        run: |
          echo "Recent commits:"
          git log --oneline -5

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_ENV: production
        run: pnpm run release

      - name: Success
        run: echo "Release completed successfully!"
