name: Test Release

on:
  push:
    branches: [main]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'README_EN.md'
      - '.github/workflows/test-release.yml'

jobs:
  test-release:
    name: Test Release Process
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run basic checks
        run: |
          echo "Running basic checks..."
          npm run lint
          npm run type-check
          npm run format:check

      - name: Test build
        run: |
          echo "Testing build process..."
          npm run build

      - name: Dry run release
        run: |
          echo "Testing release process (dry run)..."
          npm run release -- --dry-run

      - name: Show what would be released
        run: |
          echo "=== Release Analysis ==="
          npx semantic-release --dry-run --debug

      - name: Show current version
        run: |
          echo "Current package.json version:"
          node -p "require('./package.json').version"

      - name: Show recent commits
        run: |
          echo "Recent commits:"
          git log --oneline -10
